using System.Collections.Generic;

namespace Survivalistic.Framework.Databases
{
    public class Foods
    {
        public static Dictionary<string, string> GetFoodDatabase()
        {
			Dictionary<string, string> holder = new Dictionary<string, string>();

			holder.Add("Wild Horseradish", "10/10");
			holder.Add("Daffodil", "0/0");
			holder.Add("Leek", "10/10");
			holder.Add("Dandelion", "0/0");
			holder.Add("Parsnip", "10/0");
			holder.Add("Cave Carrot", "15/0");
			holder.Add("Coconut", "5/0");
			holder.Add("Cactus Fruit", "10/10");
			holder.Add("Sap", "0/0");
			holder.Add("Anchovy", "10/0");
			holder.Add("Tuna", "10/5");
			holder.Add("Sardine", "10/5");
			holder.Add("Bream", "10/5");
			holder.Add("Largemouth Bass", "25/15");
			holder.Add("Smallmouth Bass", "25/15");
			holder.Add("Rainbow Trout", "25/15");
			holder.Add("Salmon", "25/15");
			holder.Add("Walleye", "25/15");
			holder.Add("Perch", "25/15");
			holder.Add("Carp", "25/15");
			holder.Add("Catfish", "25/15");
			holder.Add("Pike", "25/15");
			holder.Add("Sunfish", "25/15");
			holder.Add("Red Mullet", "25/15");
			holder.Add("Herring", "25/15");
			holder.Add("Eel", "35/15");
			holder.Add("Octopus", "35/15");
			holder.Add("Red Snapper", "25/15");
			holder.Add("Squid", "35/15");
			holder.Add("Seaweed", "5/0");
			holder.Add("Green Algae", "5/0");
			holder.Add("Sea Cucumber", "35/15");
			holder.Add("Super Cucumber", "50/30");
			holder.Add("Ghostfish", "25/15");
			holder.Add("White Algae", "5/0");
			holder.Add("Stonefish", "25/15");
			holder.Add("Crimsonfish", "100/100");
			holder.Add("Angler", "100/100");
			holder.Add("Ice Pip", "25/15");
			holder.Add("Lava Eel", "35/0");
			holder.Add("Legend", "100/100");
			holder.Add("Glacierfish", "100/100");
			holder.Add("Mutant Carp", "100/100");
			holder.Add("Sandfish", "25/5");
			holder.Add("Scorpion Carp", "25/5");
			holder.Add("Joja Cola", "0/50");
			holder.Add("Egg", "5/5");
			holder.Add("Large Egg", "10/7");
			holder.Add("Milk", "0/50");
			holder.Add("Large Milk", "0/75");
			holder.Add("Green Bean", "15/0");
			holder.Add("Fiddlehead Risotto", "50/0");
			holder.Add("Cauliflower", "15/5");
			holder.Add("Potato", "15/5");
			holder.Add("Fried Egg", "20/0");
			holder.Add("Omelet", "50/0");
			holder.Add("Salad", "35/25");
			holder.Add("Cheese Cauliflower", "50/0");
			holder.Add("Baked Fish", "50/0");
			holder.Add("Parsnip Soup", "30/30");
			holder.Add("Vegetable Medley", "50/0");
			holder.Add("Complete Breakfast", "50/0");
			holder.Add("Fried Calamari", "50/0");
			holder.Add("Strange Bun", "50/0");
			holder.Add("Lucky Lunch", "50/0");
			holder.Add("Fried Mushroom", "50/0");
			holder.Add("Pizza", "50/0");
			holder.Add("Bean Hotpot", "50/0");
			holder.Add("Glazed Yams", "50/0");
			holder.Add("Carp Surprise", "50/0");
			holder.Add("Hashbrowns", "50/0");
			holder.Add("Pancakes", "50/0");
			holder.Add("Salmon Dinner", "50/0");
			holder.Add("Fish Taco", "50/0");
			holder.Add("Crispy Bass", "50/0");
			holder.Add("Pepper Poppers", "35/0");
			holder.Add("Bread", "35/0");
			holder.Add("Tom Kha Soup", "30/30");
			holder.Add("Trout Soup", "30/30");
			holder.Add("Chocolate Cake", "50/0");
			holder.Add("Pink Cake", "50/0");
			holder.Add("Rhubarb Pie", "50/0");
			holder.Add("Cookie", "20/0");
			holder.Add("Spaghetti", "50/0");
			holder.Add("Fried Eel", "50/0");
			holder.Add("Spicy Eel", "50/0");
			holder.Add("Sashimi", "30/20");
			holder.Add("Maki Roll", "30/20");
			holder.Add("Tortilla", "40/10");
			holder.Add("Red Plate", "40/10");
			holder.Add("Eggplant Parmesan", "40/10");
			holder.Add("Rice Pudding", "40/10");
			holder.Add("Ice Cream", "20/50");
			holder.Add("Blueberry Tart", "20/0");
			holder.Add("Autumn's Bounty", "15/5");
			holder.Add("Pumpkin Soup", "15/50");
			holder.Add("Super Meal", "50/0");
			holder.Add("Cranberry Sauce", "25/25");
			holder.Add("Stuffing", "25/25");
			holder.Add("Farmer's Lunch", "50/0");
			holder.Add("Survival Burger", "50/0");
			holder.Add("Dish O' The Sea", "25/25");
			holder.Add("Miner's Treat", "50/0");
			holder.Add("Roots Platter", "50/0");
			holder.Add("Sugar", "5/0");
			holder.Add("Wheat Flour", "5/0");
			holder.Add("Oil", "5/25");
			holder.Add("Garlic", "20/10");
			holder.Add("Kale", "20/10");
			holder.Add("Rhubarb", "20/10");
			holder.Add("Melon", "20/10");
			holder.Add("Tomato", "20/10");
			holder.Add("Morel", "20/10");
			holder.Add("Blueberry", "20/10");
			holder.Add("Fiddlehead Fern", "20/10");
			holder.Add("Hot Pepper", "20/10");
			holder.Add("Wheat", "5/0");
			holder.Add("Radish", "20/10");
			holder.Add("Red Cabbage", "20/10");
			holder.Add("Starfruit", "40/0");
			holder.Add("Corn", "20/10");
			holder.Add("Eggplant", "20/10");
			holder.Add("Artichoke", "20/10");
			holder.Add("Pumpkin", "20/10");
			holder.Add("Bok Choy", "20/10");
			holder.Add("Yam", "20/10");
			holder.Add("Chanterelle", "20/10");
			holder.Add("Cranberries", "20/10");
			holder.Add("Holly", "20/10");
			holder.Add("Beet", "20/10");
			holder.Add("Salmonberry", "10/10");
			holder.Add("Amaranth", "20/10");
			holder.Add("Pale Ale", "0/50");
			holder.Add("Hops", "20/10");
			holder.Add("Void Egg", "25/10");
			holder.Add("Mayonnaise", "5/25");
			holder.Add("Duck Mayonnaise", "5/25");
			holder.Add("Void Mayonnaise", "5/35");
			holder.Add("Pickles", "5/20");
			holder.Add("Beer", "0/50");
			holder.Add("Wine", "0/100");
			holder.Add("Juice", "0/100");
			holder.Add("Coffee", "0/100");
			holder.Add("Spice Berry", "10/10");
			holder.Add("Grape", "10/10");
			holder.Add("Spring Onion", "10/10");
			holder.Add("Strawberry", "10/10");
			holder.Add("Sweet Pea", "0/0");
			holder.Add("Field Snack", "15/0");
			holder.Add("Common Mushroom", "15/10");
			holder.Add("Wild Plum", "10/10");
			holder.Add("Hazelnut", "10/10");
			holder.Add("Blackberry", "10/10");
			holder.Add("Winter Root", "10/10");
			holder.Add("Crystal Fruit", "20/10");
			holder.Add("Snow Yam", "15/10");
			holder.Add("Vinegar", "0/35");
			holder.Add("Red Mushroom", "10/10");
			holder.Add("Sunflower", "0/0");
			holder.Add("Purple Mushroom", "10/10");
			holder.Add("Rice", "15/10");
			holder.Add("Cheese", "15/10");
			holder.Add("Goat Cheese", "15/10");
			holder.Add("Truffle", "25/10");
			holder.Add("Truffle Oil", "0/50");
			holder.Add("Stardrop", "100/100");
			holder.Add("Goat Milk", "0/50");
			holder.Add("Duck Egg", "10/7");
			holder.Add("Algae Soup", "30/30");
			holder.Add("Pale Broth", "30/30");
			holder.Add("Mead", "0/100");
			holder.Add("Tulip", "0/0");
			holder.Add("Summer Spangle", "0/0");
			holder.Add("Fairy Rose", "0/0");
			holder.Add("Blue Jazz", "0/0");
			holder.Add("Poppy", "0/0");
			holder.Add("Plum Pudding", "50/0");
			holder.Add("Artichoke Dip", "30/30");
			holder.Add("Stir Fry", "50/0");
			holder.Add("Roasted Hazelnuts", "50/0");
			holder.Add("Pumpkin Pie", "50/0");
			holder.Add("Radish Salad", "40/20");
			holder.Add("Fruit Salad", "40/20");
			holder.Add("Blackberry Cobbler", "50/0");
			holder.Add("Cranberry Candy", "50/0");
			holder.Add("Apple", "25/25");
			holder.Add("Bruschetta", "50/0");
			holder.Add("Coleslaw", "30/30");
			holder.Add("Poppyseed Muffin", "50/0");
			holder.Add("Apricot", "25/25");
			holder.Add("Orange", "25/25");
			holder.Add("Peach", "25/25");
			holder.Add("Pomegranate", "25/25");
			holder.Add("Cherry", "25/25");
			holder.Add("Bug Meat", "10/0");
			holder.Add("Sturgeon", "25/15");
			holder.Add("Tiger Trout", "25/15");
			holder.Add("Bullhead", "25/15");
			holder.Add("Tilapia", "25/15");
			holder.Add("Chub", "25/15");
			holder.Add("Dorado", "25/15");
			holder.Add("Albacore", "25/15");
			holder.Add("Shad", "25/15");
			holder.Add("Lingcod", "25/15");
			holder.Add("Halibut", "25/15");
			holder.Add("Lobster", "25/15");
			holder.Add("Crayfish", "25/15");
			holder.Add("Maple Syrup", "0/35");
			holder.Add("Chowder", "50/0");
			holder.Add("Lobster Bisque", "0/0");
			holder.Add("Fish Stew", "0/0");
			holder.Add("Escargot", "50/0");
			holder.Add("Maple Bar", "50/0");
			holder.Add("Crab Cakes", "50/0");
			holder.Add("Woodskip", "25/15");
			holder.Add("Life Elixir", "0/75");
			holder.Add("Void Salmon", "25/15");
			holder.Add("Slimejack", "25/15");

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("blueberry.LoveOfCooking"))
            {
				/*
				holder.Add("blueberry.cac.admiralpie", "1/1");
				holder.Add("blueberry.cac.applepie", "100/100");
				holder.Add("blueberry.cac.bakedpotato", "1/1");
				holder.Add("blueberry.cac.breakfast", "1/1");
				holder.Add("blueberry.cac.burger", "1/1");
				holder.Add("blueberry.cac.burntfood", "1/1");
				holder.Add("blueberry.cac.burrito", "1/1");
				holder.Add("blueberry.cac.cabbage", "1/1");
				holder.Add("blueberry.cac.cabbage Juice", "1/1");
				holder.Add("blueberry.cac.cabbage_seeds", "1/1");
				holder.Add("blueberry.cac.cabbagepot", "1/1");
				holder.Add("blueberry.cac.cake", "1/1");
				holder.Add("blueberry.cac.cake_half", "1/1");
				holder.Add("blueberry.cac.carrot", "1/1");
				holder.Add("blueberry.cac.carrot Juice", "1/1");
				holder.Add("blueberry.cac.carrot_seeds", "1/1");
				holder.Add("blueberry.cac.chocolate", "1/1");
				holder.Add("blueberry.cac.chocolatecake_half", "1/1");
				holder.Add("blueberry.cac.cider", "1/1");
				holder.Add("blueberry.cac.cookbook", "1/1");
				holder.Add("blueberry.cac.curry", "1/1");
				holder.Add("blueberry.cac.dwarfstew", "1/1");
				holder.Add("blueberry.cac.eggsando", "1/1");
				holder.Add("blueberry.cac.eggsando_half", "1/1");
				holder.Add("blueberry.cac.fritters", "1/1");
				holder.Add("blueberry.cac.gardenpie", "1/1");
				holder.Add("blueberry.cac.hotcocoa", "1/1");
				holder.Add("blueberry.cac.hunters", "1/1");
				holder.Add("blueberry.cac.kebab", "1/1");
				holder.Add("blueberry.cac.loadedpotato", "1/1");
				holder.Add("blueberry.cac.lobster", "1/1");
				holder.Add("blueberry.cac.mornay", "1/1");
				holder.Add("blueberry.cac.nettles", "1/1");
				holder.Add("blueberry.cac.nettletea", "1/1");
				holder.Add("blueberry.cac.oceanplatter", "1/1");
				holder.Add("blueberry.cac.onion", "1/1");
				holder.Add("blueberry.cac.onion Juice", "1/1");
				holder.Add("blueberry.cac.onion_seeds", "1/1");
				holder.Add("blueberry.cac.onionsoup", "1/1");
				holder.Add("blueberry.cac.pinkcake_half", "1/1");
				holder.Add("blueberry.cac.pizza_half", "1/1");
				holder.Add("blueberry.cac.porridge", "1/1");
				holder.Add("blueberry.cac.redberry", "1/1");
				holder.Add("blueberry.cac.redberry Jelly", "1/1");
				holder.Add("blueberry.cac.redberry Wine", "1/1");
				holder.Add("blueberry.cac.redberry_seeds", "1/1");
				holder.Add("blueberry.cac.redberrypie", "1/1");
				holder.Add("blueberry.cac.roast", "1/1");
				holder.Add("blueberry.cac.saladsando", "1/1");
				holder.Add("blueberry.cac.saladsando_half", "1/1");
				holder.Add("blueberry.cac.seafoodsando", "1/1");
				holder.Add("blueberry.cac.seafoodsando_half", "1/1");
				holder.Add("blueberry.cac.skewers", "1/1");
				holder.Add("blueberry.cac.stew", "1/1");
				holder.Add("blueberry.cac.stuffedpotato", "1/1");
				holder.Add("blueberry.cac.sugarcane Juice", "1/1");
				holder.Add("blueberry.cac.tropicalsalad", "1/1");
				holder.Add("blueberry.cac.unagi", "1/1");
				holder.Add("blueberry.cac.waffles", "1/1");
				holder.Add("blueberry.cac.watermelon", "1/1");
				holder.Add("blueberry.cac.watermelon Jelly", "1/1");
				holder.Add("blueberry.cac.watermelon Wine", "1/1");
				holder.Add("blueberry.cac.watermelon_half", "1/1");
				holder.Add("blueberry.cac.watermelon_seeds", "1/1");
				holder.Add("Pickled blueberry.cac.cabbage", "1/1");
				holder.Add("Pickled blueberry.cac.carrot", "1/1");
				holder.Add("Pickled blueberry.cac.onion", "1/1");
				holder.Add("Pickled blueberry.cac.sugarcane", "1/1");
				*/
			}

			return holder;
		}
    }
}
