using System.Collections.Generic;

namespace Survivalistic.Framework.Databases
{
    public class Foods
    {
        public static Dictionary<string, string> GetFoodDatabase()
        {
			Dictionary<string, string> holder = new Dictionary<string, string>();

			holder.Add("Wild Horseradish", "10/10");
			holder.Add("Leek", "10/10");
			holder.Add("Parsnip", "10/10");
			holder.Add("Cave Carrot", "15/10");
			holder.Add("Coconut", "5/0");
			holder.Add("Cactus Fruit", "10/10");
			holder.Add("Anchovy", "25/15");
			holder.Add("Tuna", "25/15");
			holder.Add("Sardine", "25/15");
			holder.Add("Bream", "25/15");
			holder.Add("Largemouth Bass", "25/15");
			holder.Add("Smallmouth Bass", "25/15");
			holder.Add("Rainbow Trout", "25/15");
			holder.Add("Salmon", "25/15");
			holder.Add("Walleye", "25/15");
			holder.Add("Perch", "25/15");
			holder.Add("Carp", "25/15");
			holder.Add("Catfish", "25/15");
			holder.Add("Pike", "25/15");
			holder.Add("Sunfish", "25/15");
			holder.Add("Red Mullet", "25/15");
			holder.Add("Herring", "25/15");
			holder.Add("Eel", "35/15");
			holder.Add("Octopus", "35/15");
			holder.Add("Red Snapper", "25/15");
			holder.Add("Squid", "35/15");
			holder.Add("Seaweed", "5/0");
			holder.Add("Green Algae", "5/0");
			holder.Add("Sea Cucumber", "35/15");
			holder.Add("Super Cucumber", "50/30");
			holder.Add("Ghostfish", "25/15");
			holder.Add("White Algae", "5/0");
			holder.Add("Stonefish", "25/15");
			holder.Add("Crimsonfish", "100/100");
			holder.Add("Angler", "100/100");
			holder.Add("Ice Pip", "25/15");
			holder.Add("Lava Eel", "35/0");
			holder.Add("Legend", "100/100");
			holder.Add("Glacierfish", "100/100");
			holder.Add("Mutant Carp", "100/100");
			holder.Add("Sandfish", "25/5");
			holder.Add("Scorpion Carp", "25/5");
			holder.Add("Joja Cola", "0/50");
			holder.Add("Egg", "5/5");
			holder.Add("Large Egg", "10/7");
			holder.Add("Milk", "0/50");
			holder.Add("Large Milk", "0/75");
			holder.Add("Green Bean", "15/0");
			holder.Add("Fiddlehead Risotto", "50/0");
			holder.Add("Cauliflower", "15/5");
			holder.Add("Potato", "15/5");
			holder.Add("Fried Egg", "20/0");
			holder.Add("Omelet", "50/0");
			holder.Add("Salad", "35/25");
			holder.Add("Cheese Cauliflower", "50/0");
			holder.Add("Baked Fish", "50/0");
			holder.Add("Parsnip Soup", "30/30");
			holder.Add("Vegetable Medley", "50/0");
			holder.Add("Complete Breakfast", "50/0");
			holder.Add("Fried Calamari", "50/0");
			holder.Add("Strange Bun", "50/0");
			holder.Add("Lucky Lunch", "50/0");
			holder.Add("Fried Mushroom", "50/0");
			holder.Add("Pizza", "50/0");
			holder.Add("Bean Hotpot", "50/0");
			holder.Add("Glazed Yams", "50/0");
			holder.Add("Carp Surprise", "50/0");
			holder.Add("Hashbrowns", "50/0");
			holder.Add("Pancakes", "50/0");
			holder.Add("Salmon Dinner", "50/0");
			holder.Add("Fish Taco", "50/0");
			holder.Add("Crispy Bass", "50/0");
			holder.Add("Pepper Poppers", "35/0");
			holder.Add("Bread", "35/0");
			holder.Add("Tom Kha Soup", "30/30");
			holder.Add("Trout Soup", "30/30");
			holder.Add("Chocolate Cake", "50/0");
			holder.Add("Pink Cake", "50/0");
			holder.Add("Rhubarb Pie", "50/0");
			holder.Add("Cookie", "20/0");
			holder.Add("Spaghetti", "50/0");
			holder.Add("Fried Eel", "50/0");
			holder.Add("Spicy Eel", "50/0");
			holder.Add("Sashimi", "30/20");
			holder.Add("Maki Roll", "30/20");
			holder.Add("Tortilla", "40/10");
			holder.Add("Red Plate", "40/10");
			holder.Add("Eggplant Parmesan", "40/10");
			holder.Add("Rice Pudding", "40/10");
			holder.Add("Ice Cream", "20/50");
			holder.Add("Blueberry Tart", "20/0");
			holder.Add("Autumn's Bounty", "15/5");
			holder.Add("Pumpkin Soup", "15/50");
			holder.Add("Super Meal", "50/0");
			holder.Add("Cranberry Sauce", "25/25");
			holder.Add("Stuffing", "25/25");
			holder.Add("Farmer's Lunch", "50/0");
			holder.Add("Survival Burger", "50/0");
			holder.Add("Dish O' The Sea", "25/25");
			holder.Add("Miner's Treat", "50/0");
			holder.Add("Roots Platter", "50/0");
			holder.Add("Sugar", "5/0");
			holder.Add("Wheat Flour", "5/0");
			holder.Add("Oil", "5/25");
			holder.Add("Garlic", "20/10");
			holder.Add("Kale", "20/10");
			holder.Add("Rhubarb", "20/10");
			holder.Add("Melon", "20/10");
			holder.Add("Tomato", "20/10");
			holder.Add("Morel", "20/10");
			holder.Add("Blueberry", "20/10");
			holder.Add("Fiddlehead Fern", "20/10");
			holder.Add("Hot Pepper", "20/10");
			holder.Add("Wheat", "5/0");
			holder.Add("Radish", "20/10");
			holder.Add("Red Cabbage", "20/10");
			holder.Add("Starfruit", "40/0");
			holder.Add("Corn", "20/10");
			holder.Add("Eggplant", "20/10");
			holder.Add("Artichoke", "20/10");
			holder.Add("Pumpkin", "20/10");
			holder.Add("Bok Choy", "20/10");
			holder.Add("Yam", "20/10");
			holder.Add("Chanterelle", "20/10");
			holder.Add("Cranberries", "20/10");
			holder.Add("Holly", "20/10");
			holder.Add("Beet", "20/10");
			holder.Add("Salmonberry", "10/10");
			holder.Add("Amaranth", "20/10");
			holder.Add("Pale Ale", "0/50");
			holder.Add("Hops", "20/10");
			holder.Add("Void Egg", "25/10");
			holder.Add("Mayonnaise", "5/25");
			holder.Add("Duck Mayonnaise", "5/25");
			holder.Add("Void Mayonnaise", "5/35");
			holder.Add("Pickles", "5/20");
			holder.Add("Beer", "0/50");
			holder.Add("Wine", "0/100");
			holder.Add("Juice", "0/100");
			holder.Add("Coffee", "0/100");
			holder.Add("Spice Berry", "10/10");
			holder.Add("Grape", "10/10");
			holder.Add("Spring Onion", "10/10");
			holder.Add("Strawberry", "10/10");
			holder.Add("Field Snack", "15/0");
			holder.Add("Common Mushroom", "15/10");
			holder.Add("Wild Plum", "10/10");
			holder.Add("Hazelnut", "10/10");
			holder.Add("Blackberry", "10/10");
			holder.Add("Winter Root", "10/10");
			holder.Add("Crystal Fruit", "20/10");
			holder.Add("Snow Yam", "15/10");
			holder.Add("Vinegar", "0/35");
			holder.Add("Red Mushroom", "10/10");
			holder.Add("Purple Mushroom", "10/10");
			holder.Add("Rice", "15/10");
			holder.Add("Cheese", "15/10");
			holder.Add("Goat Cheese", "15/10");
			holder.Add("Truffle", "25/10");
			holder.Add("Truffle Oil", "0/50");
			holder.Add("Stardrop", "100/100");
			holder.Add("Goat Milk", "0/50");
			holder.Add("Duck Egg", "10/7");
			holder.Add("Algae Soup", "30/30");
			holder.Add("Pale Broth", "30/30");
			holder.Add("Mead", "0/100");
			holder.Add("Plum Pudding", "50/0");
			holder.Add("Artichoke Dip", "30/30");
			holder.Add("Stir Fry", "50/0");
			holder.Add("Roasted Hazelnuts", "50/0");
			holder.Add("Pumpkin Pie", "50/0");
			holder.Add("Radish Salad", "40/20");
			holder.Add("Fruit Salad", "40/20");
			holder.Add("Blackberry Cobbler", "50/0");
			holder.Add("Cranberry Candy", "50/0");
			holder.Add("Apple", "25/25");
			holder.Add("Bruschetta", "50/0");
			holder.Add("Coleslaw", "30/30");
			holder.Add("Poppyseed Muffin", "50/0");
			holder.Add("Apricot", "25/25");
			holder.Add("Orange", "25/25");
			holder.Add("Peach", "25/25");
			holder.Add("Pomegranate", "25/25");
			holder.Add("Cherry", "25/25");
			holder.Add("Bug Meat", "10/0");
			holder.Add("Sturgeon", "25/15");
			holder.Add("Tiger Trout", "25/15");
			holder.Add("Bullhead", "25/15");
			holder.Add("Tilapia", "25/15");
			holder.Add("Chub", "25/15");
			holder.Add("Dorado", "25/15");
			holder.Add("Albacore", "25/15");
			holder.Add("Shad", "25/15");
			holder.Add("Lingcod", "25/15");
			holder.Add("Halibut", "25/15");
			holder.Add("Lobster", "25/15");
			holder.Add("Crayfish", "25/15");
			holder.Add("Maple Syrup", "0/35");
			holder.Add("Chowder", "50/0");
			holder.Add("Lobster Bisque", "25/25");
			holder.Add("Fish Stew", "25/25");
			holder.Add("Escargot", "50/0");
			holder.Add("Maple Bar", "50/0");
			holder.Add("Crab Cakes", "50/0");
			holder.Add("Woodskip", "25/15");
			holder.Add("Life Elixir", "0/75");
			holder.Add("Void Salmon", "25/15");
			holder.Add("Slimejack", "25/15");

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("FlashShifter.JA.SVE"))
			{
				holder.Add("Aegis Elixir", "0/75");
				holder.Add("Aged Blue Moon Wine", "0/100");
				holder.Add("Armor Elixir", "0/75");
				holder.Add("Baby Lunaloo", "15/10");
				holder.Add("Baked Berry Oatmeal", "0/0");
				holder.Add("Barbarian Elixir", "0/75");
				holder.Add("Big Bark Burger", "50/0");
				holder.Add("Blue Moon Wine", "0/100");
				holder.Add("Bonefish", "25/15");
				holder.Add("Butterfish", "25/15");
				holder.Add("Clownfish", "25/15");
				holder.Add("Daggerfish", "25/15");
				holder.Add("Dewdrop Berry", "15/10");
				holder.Add("Frog", "10/5");
				holder.Add("Frog Legs", "10/5");
				holder.Add("Gemfish", "25/15");
				holder.Add("Glazed Butterfish", "25/15");
				holder.Add("Goldenfish", "25/15");
				holder.Add("Grampleton Orange Chicken", "35/0");
				holder.Add("Gravity Elixir", "0/75");
				holder.Add("Green Mushroom", "35/15");
				holder.Add("Haste Elixir", "0/75");
				holder.Add("Hero Elixir", "0/75");
				holder.Add("Joja Berry", "0/50");
				holder.Add("Joja Veggie", "0/50");
				holder.Add("King Salmon", "25/15");
				holder.Add("Kittyfish", "25/15");
				holder.Add("Lightning Elixir", "0/75");
				holder.Add("Lunaloo", "25/15");
				holder.Add("Meteor Carp", "25/15");
				holder.Add("Minnow", "15/10");
				holder.Add("Monster Fruit", "10/10");
				holder.Add("Monster Mushroom", "10/10");
				holder.Add("Puppyfish", "25/15");
				holder.Add("Radioactive Bass", "25/15");
				holder.Add("Razor Trout", "25/15");
				holder.Add("Sea Sponge", "25/25");
				holder.Add("Seahorse", "25/10");
				holder.Add("Shiny Lunaloo", "25/15");
				holder.Add("Slime Berry", "25/15");
				holder.Add("Starfish", "25/15");
				holder.Add("Super Joja Cola", "0/100");
				holder.Add("Torpedo Trout", "25/15");
				holder.Add("Undeadfish", "25/15");
				holder.Add("Void Delight", "35/0");
				holder.Add("Void Eel", "25/15");
				holder.Add("Void Root", "15/10");
				holder.Add("Void Salmon Sushi", "30/20");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("ppja.starbrewvalley.DGA"))
            {
				holder.Add("OBJECT", "999/999");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("ppja.morerecipes.DGA"))
			{
				holder.Add("OBJECT", "999/999");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("ppja.evenmorerecipes.DGA"))
			{
				holder.Add("OBJECT", "999/999");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("ppja.freshmeat.DGA"))
			{
				holder.Add("OBJECT", "999/999");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("ppja.fruitsandveggies"))
            {
				holder.Add("Adzuki Bean", "15/5");
				holder.Add("Aloe", "15/5");
				holder.Add("Asparagus", "15/5");
				holder.Add("Bamboo", "15/5");
				holder.Add("Barley", "15/5");
				holder.Add("Basil", "15/5");
				holder.Add("Red Bell Pepper", "15/5");
				holder.Add("Green Bell Pepper", "15/5");
				holder.Add("Yellow Bell Pepper", "15/5");
				holder.Add("Orange Bell Pepper", "15/5");
				holder.Add("Blue Agave", "15/5");
				holder.Add("Broccoli", "15/5");
				holder.Add("Buckwheat", "15/5");
				holder.Add("Butternut Squash", "15/5");
				holder.Add("Cabbage", "15/5");
				holder.Add("Cactus Flower", "15/5");
				holder.Add("Carrot", "15/5");
				holder.Add("Cassava", "15/5");
				holder.Add("Celery", "15/5");
				holder.Add("Chickpea", "15/5");
				holder.Add("Chives", "15/5");
				holder.Add("Cotton Boll", "15/5");
				holder.Add("Cucumber", "15/5");
				holder.Add("Durum", "15/5");
				holder.Add("Elderberry", "15/5");
				holder.Add("Fennel", "15/5");
				holder.Add("Ginseng", "15/5");
				holder.Add("Gooseberry", "15/5");
				holder.Add("Green Peas", "15/5");
				holder.Add("Habanero", "15/5");
				holder.Add("Jalapeno", "15/5");
				holder.Add("Juniper Berry", "15/5");
				holder.Add("Kidney Bean", "15/5");
				holder.Add("Kiwi", "15/5");
				holder.Add("Lettuce", "15/5");
				holder.Add("Licorice Root", "15/5");
				holder.Add("Maguey", "15/5");
				holder.Add("Mint", "15/5");
				holder.Add("Muskmelon", "15/5");
				holder.Add("Navy Bean", "15/5");
				holder.Add("Oat", "15/5");
				holder.Add("Okra", "15/5");
				holder.Add("Onion", "15/5");
				holder.Add("Oregano", "15/5");
				holder.Add("Parsley", "15/5");
				holder.Add("Passion Fruit", "15/5");
				holder.Add("Peanut", "15/5");
				holder.Add("Perilla leaf", "15/5");
				holder.Add("Quinoa", "15/5");
				holder.Add("Rapeseed Flower", "15/5");
				holder.Add("Raspberry", "15/5");
				holder.Add("Red Onion", "15/5");
				holder.Add("Rosemary", "15/5");
				holder.Add("Sage", "15/5");
				holder.Add("Shallot", "15/5");
				holder.Add("Shiitake Mushroom", "15/5");
				holder.Add("Soybean", "15/5");
				holder.Add("Spinach", "15/5");
				holder.Add("Sugar Beet", "15/5");
				holder.Add("Sugar Cane", "15/5");
				holder.Add("Sulfur Shelf Mushroom", "15/5");
				holder.Add("Sweet Canary Melon", "15/5");
				holder.Add("Sweet Potato", "15/5");
				holder.Add("Tabasco Pepper", "15/5");
				holder.Add("Thyme", "15/5");
				holder.Add("Wasaby Root", "15/5");
				holder.Add("Watermelon", "15/5");
				holder.Add("Zucchini", "15/5");
				holder.Add("Serrano Chile", "15/5");
				holder.Add("Scotch Bonnet", "15/5");
				holder.Add("Poblano Chile", "15/5");
				holder.Add("Carolina Reaper", "15/5");
				holder.Add("Ghost Pepper", "15/5");
				holder.Add("Bay", "15/5");
				holder.Add("Catnip", "15/5");
				holder.Add("Champagne Grape", "15/5");
				holder.Add("Wormwood", "15/5");
				holder.Add("Mung Bean", "15/5");
				holder.Add("Ube", "15/5");
				holder.Add("White Onion", "15/5");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("MelindaC.FizzyDrinks"))
			{
				holder.Add("Apple Beer", "0/50");
				holder.Add("Banana Marble Soda", "0/50");
				holder.Add("Birch Bark", "0/50");
				holder.Add("Birch Beer", "0/50");
				holder.Add("Birch Extract", "0/50");
				holder.Add("Bitter Orange", "0/50");
				holder.Add("Blue Bubblegum Soda", "0/50");
				holder.Add("Blueberry Marble Soda", "0/50");
				holder.Add("Burdock Root", "0/50");
				holder.Add("Butterscotch Soda", "0/50");
				holder.Add("Cane Sugar Soda", "0/50");
				holder.Add("Cappuccino Soda", "0/50");
				holder.Add("Champagne Soda", "0/50");
				holder.Add("Chili Oil Marble Soda", "0/50");
				holder.Add("Chinotto Extract", "0/50");
				holder.Add("Chinotto Soda", "0/50");
				holder.Add("Clear Joja Syrup", "0/50");
				holder.Add("Coconut Marble Soda", "0/50");
				holder.Add("Cucumber Soda", "0/50");
				holder.Add("Dandelion And Burdock Infusion", "0/50");
				holder.Add("Dandelion And Burdock Soda", "0/50");
				holder.Add("Dreamsicle Float", "0/50");
				holder.Add("Espresso Soda", "0/50");
				holder.Add("Fize Blackberry Ginger Ale", "0/50");
				holder.Add("Fize Cranberry Ginger Ale", "0/50");
				holder.Add("Fize Green Tea Ginger Ale", "0/50");
				holder.Add("Ginger Brew", "0/50");
				holder.Add("Ginger Extract", "0/50");
				holder.Add("Ginseng Soda", "0/50");
				holder.Add("Grape Marble Soda", "0/50");
				holder.Add("Green Tea Soda", "0/50");
				holder.Add("Guarana", "0/50");
				holder.Add("Guarana Extract", "0/50");
				holder.Add("Guarana Soda", "0/50");
				holder.Add("Hard Chinotto Soda", "0/50");
				holder.Add("Hard Ginger Brew", "0/50");
				holder.Add("Hard Root Beer", "0/50");
				holder.Add("Jamaican Ginger Brew", "0/50");
				holder.Add("Joja Cherry", "0/50");
				holder.Add("Joja Gold", "0/50");
				holder.Add("Joja Mate", "0/50");
				holder.Add("Joja Peach", "0/50");
				holder.Add("Joja Red", "0/50");
				holder.Add("Joja Strawberry", "0/50");
				holder.Add("Joja Syrup", "0/50");
				holder.Add("Joja Tackleberry", "0/50");
				holder.Add("Jojanana Soda", "0/50");
				holder.Add("Jojango Soda", "0/50");
				holder.Add("Julmust Soda", "0/50");
				holder.Add("Mango Marble Soda", "0/50");
				holder.Add("Maple Cream Soda", "0/50");
				holder.Add("Maple Soda", "0/50");
				holder.Add("Matcha Marble Soda", "0/50");
				holder.Add("Melon Marble Soda", "0/50");
				holder.Add("Muscat Grape", "0/50");
				holder.Add("Muscat Marble Soda", "0/50");
				holder.Add("Old Fashioned Sarsaparilla", "0/50");
				holder.Add("Orange Marble Soda", "0/50");
				holder.Add("Original Marble Soda", "0/50");
				holder.Add("Peach Marble Soda", "0/50");
				holder.Add("Pineapple Marble Soda", "0/50");
				holder.Add("Plum Marble Soda", "0/50");
				holder.Add("Pomegranate Marble Soda", "0/50");
				holder.Add("Red Sorrel Leaf", "0/50");
				holder.Add("Red Sorrel Soda", "0/50");
				holder.Add("Red Sorrel Syrup", "0/50");
				holder.Add("Root Beer", "0/50");
				holder.Add("Root Beer Float", "0/50");
				holder.Add("Root Beer Ice Cream", "0/50");
				holder.Add("Sarsaparilla", "0/50");
				holder.Add("Sassafras Root", "0/50");
				holder.Add("Spruce Beer", "0/50");
				holder.Add("Spruce Essence", "0/50");
				holder.Add("Spruce Tips", "0/50");
				holder.Add("Stevia Extract", "0/50");
				holder.Add("Stevia Plant", "0/50");
				holder.Add("Stevia Soda", "0/50");
				holder.Add("Strawberry Marble Soda", "0/50");
				holder.Add("Tackleberry Syrup", "0/50");
				holder.Add("Yerba Mate Extract", "0/50");
				holder.Add("Yerba Mate Leaves", "0/50");
				holder.Add("Yerba Mate Soda", "0/50");
				holder.Add("Yerba Mate Tea", "0/50");
				holder.Add("Yogurt Marble Soda", "0/50");
				holder.Add("Yuzu Marble Soda", "0/50");
			}

			if (ModEntry.instance.Helper.ModRegistry.IsLoaded("blueberry.LoveOfCooking"))
            {
				/*
				holder.Add("blueberry.cac.admiralpie", "50/0");
				holder.Add("blueberry.cac.applepie", "50/0");
				holder.Add("blueberry.cac.bakedpotato", "50/0");
				holder.Add("blueberry.cac.breakfast", "50/0");
				holder.Add("blueberry.cac.burger", "50/0");
				holder.Add("blueberry.cac.burntfood", "50/0");
				holder.Add("blueberry.cac.burrito", "50/0");
				holder.Add("blueberry.cac.cabbage", "50/0");
				holder.Add("blueberry.cac.cabbage Juice", "50/0");
				holder.Add("blueberry.cac.cabbage_seeds", "50/0");
				holder.Add("blueberry.cac.cabbagepot", "50/0");
				holder.Add("blueberry.cac.cake", "50/0");
				holder.Add("blueberry.cac.cake_half", "50/0");
				holder.Add("blueberry.cac.carrot", "50/0");
				holder.Add("blueberry.cac.carrot Juice", "50/0");
				holder.Add("blueberry.cac.carrot_seeds", "50/0");
				holder.Add("blueberry.cac.chocolate", "50/0");
				holder.Add("blueberry.cac.chocolatecake_half", "50/0");
				holder.Add("blueberry.cac.cider", "50/0");
				holder.Add("blueberry.cac.cookbook", "50/0");
				holder.Add("blueberry.cac.curry", "50/0");
				holder.Add("blueberry.cac.dwarfstew", "50/0");
				holder.Add("blueberry.cac.eggsando", "50/0");
				holder.Add("blueberry.cac.eggsando_half", "50/0");
				holder.Add("blueberry.cac.fritters", "50/0");
				holder.Add("blueberry.cac.gardenpie", "50/0");
				holder.Add("blueberry.cac.hotcocoa", "50/0");
				holder.Add("blueberry.cac.hunters", "50/0");
				holder.Add("blueberry.cac.kebab", "50/0");
				holder.Add("blueberry.cac.loadedpotato", "50/0");
				holder.Add("blueberry.cac.lobster", "50/0");
				holder.Add("blueberry.cac.mornay", "50/0");
				holder.Add("blueberry.cac.nettles", "50/0");
				holder.Add("blueberry.cac.nettletea", "50/0");
				holder.Add("blueberry.cac.oceanplatter", "50/0");
				holder.Add("blueberry.cac.onion", "50/0");
				holder.Add("blueberry.cac.onion Juice", "50/0");
				holder.Add("blueberry.cac.onion_seeds", "50/0");
				holder.Add("blueberry.cac.onionsoup", "50/0");
				holder.Add("blueberry.cac.pinkcake_half", "50/0");
				holder.Add("blueberry.cac.pizza_half", "50/0");
				holder.Add("blueberry.cac.porridge", "50/0");
				holder.Add("blueberry.cac.redberry", "50/0");
				holder.Add("blueberry.cac.redberry Jelly", "50/0");
				holder.Add("blueberry.cac.redberry Wine", "50/0");
				holder.Add("blueberry.cac.redberry_seeds", "50/0");
				holder.Add("blueberry.cac.redberrypie", "50/0");
				holder.Add("blueberry.cac.roast", "50/0");
				holder.Add("blueberry.cac.saladsando", "50/0");
				holder.Add("blueberry.cac.saladsando_half", "50/0");
				holder.Add("blueberry.cac.seafoodsando", "50/0");
				holder.Add("blueberry.cac.seafoodsando_half", "50/0");
				holder.Add("blueberry.cac.skewers", "50/0");
				holder.Add("blueberry.cac.stew", "50/0");
				holder.Add("blueberry.cac.stuffedpotato", "50/0");
				holder.Add("blueberry.cac.sugarcane Juice", "50/0");
				holder.Add("blueberry.cac.tropicalsalad", "50/0");
				holder.Add("blueberry.cac.unagi", "50/0");
				holder.Add("blueberry.cac.waffles", "50/0");
				holder.Add("blueberry.cac.watermelon", "50/0");
				holder.Add("blueberry.cac.watermelon Jelly", "50/0");
				holder.Add("blueberry.cac.watermelon Wine", "50/0");
				holder.Add("blueberry.cac.watermelon_half", "50/0");
				holder.Add("blueberry.cac.watermelon_seeds", "50/0");
				holder.Add("Pickled blueberry.cac.cabbage", "50/0");
				holder.Add("Pickled blueberry.cac.carrot", "50/0");
				holder.Add("Pickled blueberry.cac.onion", "50/0");
				holder.Add("Pickled blueberry.cac.sugarcane", "50/0");
				*/
			}

			return holder;
		}
    }
}
